"""update

Revision ID: 461cda0f67ec
Revises: 92cbf6f70a73
Create Date: 2024-05-20 11:59:56.864362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461cda0f67ec'
down_revision = '92cbf6f70a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('office_supply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('links', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office_supply', schema=None) as batch_op:
        batch_op.drop_column('links')
        batch_op.drop_column('description')

    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
