"""Added tags to OfficeSupply

Revision ID: 92cbf6f70a73
Revises: 
Create Date: 2024-04-10 13:42:32.698738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cbf6f70a73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('office_supplies')
    with op.batch_alter_table('office_supply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.alter_column('min_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office_supply', schema=None) as batch_op:
        batch_op.alter_column('min_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('tags')

    op.create_table('office_supplies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='office_supplies_pkey')
    )
    # ### end Alembic commands ###
